language: android
jdk: oraclejdk7

android:
  components:
    - android-23
    - Build-tools 
    - extra-android-m2repository
    - extra-google-m2repository
script: 
    - echo "Travis branch is $TRAVIS_BRANCH"
    - echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"
    - ./gradlew assembleRelease --info
